name: CompatHelper
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
jobs:
  CompatHelper:
    runs-on: self-hosted
    steps:
      - name: Pkg.add("CompatHelper")
        run: %JULIA_191% -e 'using Pkg; Pkg.add("CompatHelper")'
      - name: CompatHelper.main()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: %JULIA_191% -e 'using CompatHelper; CompatHelper.main()'
